### ISSUE TITLE
aXeError: task aXe_GOL2AF when running ACS/WFC/G800L-F775W data (old MAST files before pipeline update)

### ISSUE THREAD

**Issue by bkornpob** [spacetelescope/hstaxe#10]
Solved: wrong calibration filepaths were provided causing the problem.

This error happened when I ran pyaxe on ACS/WFC/G800L-F775W. Data were downloaded from MAST (before the pipeline update), PID = 15401, filters = ['G800L','F775W'], SUBARRAY = False. This is WR96, and the data were used in a recent ISR. Note that, the data set composes of both subarray and full images. Only full images were used in the run.

> ---------------------------------------------------------------------------
> aXeError                                  Traceback (most recent call last)
> <ipython-input-32-7be2a053baad> in <module>
>       5                      backims="WFC3.IR.G141.sky.V1.0.fits",
>       6                      norm=False,
> ----> 7                      mfwhm=3.0)
> 
> ~/anaconda3/envs/pyaxe/lib/python3.7/site-packages/pyaxe/axesrc/axetasks.py in axeprep(inlist, configs, wavelength, backgr, backims, backped, mfwhm, norm, gcorr)
>     168                                            gcorr=gcorr)
>     169 
> --> 170         aXePrep.run()
>     171         del aXePrep
>     172 
> 
> ~/anaconda3/envs/pyaxe/lib/python3.7/site-packages/pyaxe/axesrc/axepreptor.py in run(self)
>     546         # make a background PET if necessary
>     547         if 'backgr' in self.params and self.params['backgr']:
> --> 548             self._subtract_background(ext_info)
>     549 
>     550         # make a background PET if necessary
> 
> ~/anaconda3/envs/pyaxe/lib/python3.7/site-packages/pyaxe/axesrc/axepreptor.py in _subtract_background(self, ext_info)
>     377 
>     378         # generate the mask image
> --> 379         self._make_mask()
>     380 
>     381         # check whether we have NICMOS
> 
> ~/anaconda3/envs/pyaxe/lib/python3.7/site-packages/pyaxe/axesrc/axepreptor.py in _make_mask(self)
>     147                         dmag=self.dmag,
>     148                         out_af=None,
> --> 149                         in_gol=None)
>     150 
>     151         #  run BACKEST
> 
> ~/anaconda3/envs/pyaxe/lib/python3.7/site-packages/pyaxe/axesrc/axetasks.py in gol2af(grism, config, mfwhm, back, orient, slitless_geom, exclude, lambda_mark, dmag, out_af, in_gol, silent)
>     461                                   in_gol=in_gol,
>     462                                   out_af=out_af)
> --> 463     gol2af.runall(silent)
>     464 
>     465 
> 
> ~/anaconda3/envs/pyaxe/lib/python3.7/site-packages/pyaxe/axesrc/axelowlev.py in runall(self, silent)
>     150             self._cleanup()
>     151         else:
> --> 152             self._report_all(silent)
>     153 
>     154         # return the result
> 
> ~/anaconda3/envs/pyaxe/lib/python3.7/site-packages/pyaxe/axesrc/axelowlev.py in _report_all(self, silent)
>      83         # report an error
>      84         raise aXeError("An error occurred in the aXe task: {0:s}"
> ---> 85                        .format(self.taskname))
>      86 
>      87     def run(self, silent=True):
> 
> aXeError: An error occurred in the aXe task: aXe_GOL2AF

**Comment by larrybradley** [comment]
Closed after discussion with the INS grism teams.
