### ISSUE TITLE
Cannot use local background function

### ISSUE THREAD

**Issue by bkornpob** [spacetelescope/hstaxe#18]
I was following aXe_WFC3_Cookbook.ipynb as provided here, but wanted to turn on the local background function. So, I edited the code like this:
`axetasks.axecore('aXe.lis',
                 "G141.F140W.V4.31.conf",
                 extrfwhm=4.,
                 drzfwhm=3.,
                 back=True,
                 backfwhm=5.,
                 lambda_psf=1392.0,
                 np=10.,
                 interp='1',
                 spectr=True,
                 orient=False,
                 weights=True,
                 slitless_geom=True,
                 cont_model='gauss',
                 sampling='drizzle',
                 exclude=False)`
The code ran successfully and didn't terminate with any error. Then, I checked the OUTPUT folder and found that the code did not produce SPC files, or BCK files (as were produced by old aXe versions).

Can you tell me how to use this functionality properly in this new version? I checked with docs folder in this repository, and found that these documents might not be updated yet?

Thank you

ADDED (4 Aug 2021): @dsom-stsci tested and arrived at the same problem.

**Comment by rosteen** [comment]
Local background for WFC3 was fixed, closing this.
