### ISSUE TITLE
Documentation: link to test data is broken

### ISSUE THREAD

**Issue by steveschulze** [spacetelescope/hstaxe#96]
Hi,

The documentation (https://hstaxe.readthedocs.io/en/latest/hstaxe/installing.html) points to test data. However, the link http://axe.stsci.edu/axe/testdata.html doesn't work anymore. Where can I find the test data?

Cheers,

Steve

**Comment by rosteen** [comment]
Thanks for bringing this to our attention, I addressed this in #99.
